# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Emacs
    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            shell: powershell
            
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      MSYS2_DIR: C:\msys64

    defaults:
      run:
        shell: ${{ matrix.shell }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Emacs Igc
        # Require --with-* flags, else the deps will not be included properly
        run: |
          .\emacs-build.cmd --branch feature/igc --clone --slim --deps --build --pack-emacs

      # Upload release for each build
      - name: Upload binaries to release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./zips/*{.zip}
          file_glob: true


