# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Emacs
    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            shell: powershell
            msystem: UCRT64
            
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      MSYS2_DIR: C:\msys64

    defaults:
      run:
        shell: ${{ matrix.shell }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: ${{ matrix.msystem }}
          release: false

      # This is the shortest job, but in this case it pulls all MSYS/MINGW64
      - name: Clone Emacs
        run: .\emacs-build.cmd  --clone --repo https://github.com/emacs-mirror/emacs

      - name: Install deps
        shell: msys2 {0}
        run: |
          ./emacs-build.sh --slim --ensure

      - name: Build Emacs
        # Require --with-* flags, else the deps will not be included properly
        run: |
          .\emacs-build.cmd  --slim  --configure --build-dev 

      - name: Package Emacs
        run: |
          .\emacs-build.cmd --slim  --pack-all 

      - name: Zip the directory
        shell: msys2 {0}
        run: |
          cd /d/a/emacs-build/emacs-build/build/
          zip -r master-ucrt-x86_64-full.zip master-ucrt-x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: master-ucrt-x86_64-full.zip
          path: /d/a/emacs-build/emacs-build/build/master-ucrt-x86_64-full.zip

